<a href="https://colab.research.google.com/github/laresamdeola/Pytorch-Tutorials/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

In [ ]:
!nvidia-smi

Wed Aug  7 06:10:26 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
torch.__version__

'2.3.1+cu121'

In [ ]:
np.__version__

'1.26.4'

Tensors

In [ ]:
scalar = torch.tensor(7)

In [ ]:
print(scalar)

tensor(7)


In [ ]:
scalar.ndim

0

In [ ]:
# Vector

vector = torch.tensor([18, 20])
vector

tensor([18, 20])

In [ ]:
vector.ndim

1

In [ ]:
# Scalars = 7
# Vectors = [1, 2]
# Matrices = [[1,2], [2, 3]]
# Tensor = [[1, 2], [3, 4], [5, 6], [7, 8]]

In [ ]:
# Matrix

MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

TENSOR

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8701, 0.5425, 0.8397, 0.5248],
        [0.9469, 0.6746, 0.1966, 0.4884],
        [0.0802, 0.1434, 0.8796, 0.4470]])

In [ ]:
# Random tensor similar to an image

random_image_tensor = torch.rand(size=(3, 224, 224))

random_image_tensor.shape

torch.Size([3, 224, 224])

In [ ]:
random_image_tensor.ndim

3