<a href="https://colab.research.google.com/github/laresamdeola/Pytorch-Tutorials/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

In [3]:
!nvidia-smi

Sat Aug 10 06:08:01 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
torch.__version__

'2.3.1+cu121'

In [5]:
np.__version__

'1.26.4'

Tensors

In [6]:
scalar = torch.tensor(7)

In [7]:
print(scalar)

tensor(7)


In [8]:
scalar.ndim

0

In [9]:
# Vector

vector = torch.tensor([18, 20])
vector

tensor([18, 20])

In [10]:
vector.ndim

1

In [11]:
# Scalars = 7
# Vectors = [1, 2]
# Matrices = [[1,2], [2, 3]]
# Tensor = [[1, 2], [3, 4], [5, 6], [7, 8]]

In [12]:
# Matrix

MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

TENSOR

In [15]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors

In [18]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1963, 0.7460, 0.0324, 0.6445],
        [0.4565, 0.7364, 0.4843, 0.6872],
        [0.3885, 0.3881, 0.7515, 0.0602]])

In [19]:
# Random tensor similar to an image

random_image_tensor = torch.rand(size=(3, 224, 224))

random_image_tensor.shape

torch.Size([3, 224, 224])

In [20]:
random_image_tensor.ndim

3

Zeroes and Ones

In [21]:
zero = torch.zeros(3, 4)

In [22]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# create a tensor of all ones

ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Creating a range of tensors and tensors-like

In [24]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
one_steps_10 = torch.arange(start=10, end=101, step=10)
one_steps_10

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [26]:
# Creating tensors like

ten_zeroes = torch.zeros_like(input=one_steps_10)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

In [27]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [29]:
type(float_16_tensor)

torch.Tensor

In [30]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

Tensor Attributes

In [31]:
some_tensor = torch.rand(3, 4)

In [32]:
some_tensor

tensor([[0.2116, 0.8404, 0.0956, 0.6855],
        [0.2207, 0.7005, 0.6861, 0.3213],
        [0.9865, 0.7788, 0.4970, 0.2732]])

In [33]:
print(f'Tensor Datatype: {some_tensor.dtype}')
print(f'Tensor Shape: {some_tensor.shape}')
print(f'Tensor Device: {some_tensor.device}')

Tensor Datatype: torch.float32
Tensor Shape: torch.Size([3, 4])
Tensor Device: cpu
